MyMeetings/MyMeetings/Models/ModerationViewModels.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MyMeetings.Models
{
    public class ModerationViewModels
    {
        public class UserDetailsViewModel
        {
            public string Email { get; set; }
            public string FirstName { get; set; }
            public string SurName { get; set; }
            public List<string> Roles { get; set; }
            public string DateOfRegistration { get; set; }
            public string Gender { get; set; }
            public string DateOfBirth { get; set; }
        }
        // GET: ModerationViewModels

    }
}

MyMeetings/MyMeetings/Controllers/FindController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.ApplicationInsights.Extensibility.Implementation;
using MyMeetings.Models;
using Newtonsoft.Json;

namespace MyMeetings.Controllers
{
    public class FindController : Controller
    {
        private ApplicationDbContext DBContext = new ApplicationDbContext();

        //// GET: Find
        //public ActionResult Index()
        //{
        //    return View();
        //}
        //POST: /Account/FindUser

        [HttpPost]
        public ActionResult FindUsers(string userName, string userFirstname, string userSurname)
        {
            IEnumerable<ApplicationUser> tempUsers = DBContext.Users;
            if (userName != "") tempUsers = tempUsers.Where(u => u.UserName.ToLower().Contains(userName.ToLower()));
            if (userFirstname != "")
                tempUsers =
                    tempUsers.Where(u => !String.IsNullOrEmpty(u.FirstName))
                        .Where(u => u.FirstName.ToLower().Contains(userFirstname.ToLower()));
            if (userSurname != "")
                tempUsers =
                    tempUsers.Where(u => !String.IsNullOrEmpty(u.SurName))
                        .Where(u => u.SurName.ToLower().Contains(userSurname.ToLower()));
            tempUsers = tempUsers.OrderBy(m => m.UserName).OrderBy(m => m.FirstName).OrderBy(m => m.SurName);
            List<ApplicationUser> users = tempUsers.ToList();
            return PartialView(users);
        }
        public string Get()
        {
            return JsonConvert.SerializeObject(DBContext.Users);
        }
    }
}

MyMeetings/MyMeetings/Controllers/ModerationController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using MyMeetings.Models;
using Newtonsoft.Json;
using PagedList;

namespace MyMeetings.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class ModerationController : Controller
    {
        ApplicationUserManager UserManager = new ApplicationUserManager(new UserStore<ApplicationUser>(new ApplicationDbContext()));
        //POST
       
        public ActionResult ShowUsers(string userName,int? page)
        {
            List<ApplicationUser> result = new List<ApplicationUser>();
            if (userName.IsNullOrWhiteSpace())
            {
                result = UserManager.Users.ToList();
            }
            else
            {
                var users = UserManager.Users.Where(a => a.UserName.Contains(userName)).ToList();
            }
            int pagesize = 3;
            int pagenumber = (page ?? 1);
            return View(result.ToPagedList(pagenumber,pagesize));
        }

        public ActionResult UserDetails(string id)
        {
            ApplicationRoleManager roleManager = HttpContext.GetOwinContext().GetUserManager<ApplicationRoleManager>();
            ModerationViewModels.UserDetailsViewModel currentDetails=new ModerationViewModels.UserDetailsViewModel();
            var result = UserManager.Users.FirstOrDefault(user => user.Id == id);
            currentDetails.Email = result.Email??"";
            currentDetails.FirstName = result.FirstName;
            currentDetails.SurName = result.SurName;
            currentDetails.DateOfBirth = result.DateOfBirth.ToShortDateString()??"";
            currentDetails.DateOfRegistration = result.DateOfRegistration.ToShortDateString();
            currentDetails.Gender = result.Gender;
            List<IdentityUserRole> userRoles=new List<IdentityUserRole>();
            List<string> userRoleList=new List<string>();
            foreach (var role in roleManager.Roles)
            {
                //var userRole = role.Users.FirstOrDefault(user => user.UserId == id);
                //var roleName = DBContext.Roles.Where(r => r.Id == userRole.RoleId);
                //if(roleName)currentDetails.Roles.Add(roleName.First().Name);
                foreach (var u in role.Users)
                {
                    if (u.UserId==id) userRoleList.Add(role.Name);
                    
                }
            }
            currentDetails.Roles=userRoleList;
            return PartialView(currentDetails);
        }

      
    }
    }

MyMeetings/MyMeetings/Views/Moderation/ShowUsers.cshtml
@model PagedList.IPagedList<MyMeetings.Models.ApplicationUser>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css"/>
@{
    ViewBag.Title = "ShowUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Пользователи</h2>
<div>
    <div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>
    @using (Ajax.BeginForm("FindUsers", "Find", new AjaxOptions { UpdateTargetId = "results" }))
    {
        <table class="table">
            <thead>
                <tr>
                    <th>UserId</th>
                    <th>FirstName</th>
                    <th>SurName</th>
                    <th></th>
                </tr>
            </thead>
            <tr>
                <td>
                    <input type="text" name="userName" class="col-md-3 col-lg-3 col-xs-3"/>
                </td>
                <td>
                     <input type="text" name="userFirstname" class="col-md-3 col-lg-3 col-xs-3"/>
                </td>
                <td>
                    <input type="text" name="userSurname" class="col-md-3 col-lg-3 col-xs-3"/>
                </td>
                <td>
                    <input type="submit" value="Find"/>
                </td>
            </tr>
        </table>
    }
</div>
<div id="results">
    <table class="table table-striped">
        <thead>
        <tr>
            <th>Отметка</th>
            <th>UseId</th>
            <th>FirstName</th>
            <th>SurName</th>

        </tr>
        </thead>
        @foreach (var m in Model)
        {
            <tr>
                <td>
                    <input id="@m.Id" type="radio" name="role" value=@m.Id class="user-id"/>
                </td>
                <td>
                    <p>@m.UserName </p>
                </td>
                <td>
                    <p>@m.FirstName </p>
                </td>
                <td>
                    <p>@m.SurName </p>
                </td>
                <td>
                    <a class="userInfo" href='@Url.Action("UserDetails", "Moderation", new {id = m.Id})'>
                        <img src="~/Content/images/UserInfo.png" width="18" height="18">
                    </a>
                </td>
            </tr>
        }
    </table>

    <label class="checkbox-inline" id="list-of-roles">

    </label>
    <p>
        <a class="btn btn-default btn-save">Save</a>
    </p>

    <br/> Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("ShowUsers", new {page}))
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/CommonScripts/Manage/ValidateFileFormat.js");
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/scripts/commonscripts/roles/roleanduserhandler.js")
    @Styles.Render("~/content/pagestyles/show-users-page.css")
    <script type="text/javascript">

        $(function() {
            $.ajaxSetup({ cache: false });
            $(".userInfo").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}

MyMeetings/MyMeetings/Views/Moderation/UserDetails.cshtml
@using System.Net.Configuration
@model MyMeetings.Models.ModerationViewModels.UserDetailsViewModel

<div class="modal-content">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" area-hidden="true">X</button>
        <h4>Информация пользователя</h4>
    </div>
    <div class="modal-body">
        <dl class="dl-horizontal">
            <dt>user E-mail:</dt>
            <dd>@Html.DisplayFor(model => model.Email)</dd>
            <dt>Firstname</dt>
            <dd>@Html.DisplayFor(model => model.FirstName)</dd>
            <dt>Surname</dt>
            <dd>@Html.DisplayFor(model => model.SurName)</dd>
            <dt>Date of birth</dt>
            <dd>@Html.DisplayFor(model => model.DateOfBirth)</dd>
            <dt>Date of registration</dt>
            <dd>@Html.DisplayFor(model => model.DateOfRegistration)</dd>
            <dt>Gender</dt>
            <dd>@Html.DisplayFor(model => model.Gender)</dd>
            <dt>Roles</dt>
                @foreach (var item in Model.Roles)

                { 
                <dd>
                    <p>@item</p>
                    </dd>
                }
        </dl>
    </div>
</div>