MyMeetings/MyMeetings/Models/PublicationViewModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Claims;
using System.Web;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Security.Principal;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Microsoft.AspNet.Identity;
using System.ComponentModel.DataAnnotations.Schema;

namespace MyMeetings.Models
{
    public class PublicationViewModels
    {
        public class PartialPublication
        {
            public string PublicationId;
            public string ImagePath;
            public string Creator;
            public string DateOfPublication;
            public string PublicationName;
            public string DateOfMeet;
            public List<ApplicationUser> Subscribers;
            public string PublicationText;

            public bool IsSubscribedUser
            {
                get
                {
                    string userId = ClaimsPrincipal.Current.Identity.GetUserId();
                    return Subscribers.Any(user=>user.Id==userId);
                }
            }
        }
        public class CreatePublicationModelView
        {
            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 2)]
            [Display(Name = "Publication name")]
            public string PublicationName { get; set; }

            [Required]
            [StringLength(500, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 10)]
            [Display(Name = "Description of publication")]
            public string Text { get; set; }
            [Required]
            [Display(Name = "Date of meeting")]
            [DataType(DataType.DateTime)]
            [DisplayFormat(DataFormatString = "{0:MM'/'dd'/'yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
            public DateTime DateOfMeeting { get; set; }
            [Required]
            [Display(Name = "Category")]
            public string CategoryID { get; set; }
            [NotMapped]
            public SelectList Categories { get; set; }
        }
        public class ShortPublicationModelView {
            public string PublicationId;
            public string ImagePath;
            public string Creator;
            public string DateOfPublication;
            public string PublicationName;
            public string DateOfMeet;
            public string Category;
        }
    }
    }

MyMeetings/MyMeetings/Controllers/PublicationsController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security.Provider;
using MyMeetings.Models;
using PagedList;


namespace MyMeetings.Controllers
{
    [Authorize]
    public class PublicationsController : Controller
    {
        private ApplicationDbContext DB = new ApplicationDbContext();
        public ActionResult Create()
        {
            PublicationViewModels.CreatePublicationModelView model = new PublicationViewModels.CreatePublicationModelView();
            model.Categories = new SelectList(DB.PublicationCategories, "Id", "Name");
            return View(model);
        }

        [HttpPost]

        public ActionResult Create(PublicationViewModels.CreatePublicationModelView model)
        {

            ApplicationUserManager userManager =
                  new ApplicationUserManager(new UserStore<ApplicationUser>(DB));
            if (ModelState.IsValid)
            {
                string currentId = User.Identity.GetUserId();
                ApplicationUser currentAuthor = userManager.Users.FirstOrDefault(user => user.Id == currentId);
                var publication = new Publication()
                {
                    Name = model.PublicationName,
                    DateOfMeeting = model.DateOfMeeting,
                    Text = model.Text,
                    Author = currentAuthor,
                    Category = DB.PublicationCategories.FirstOrDefault(p => p.Id == model.CategoryID.ToString()),
                    Subscriptions = new List<ApplicationUser>() { currentAuthor }
                };
               
                HttpPostedFileBase hpf = Request.Files["imagefile"] as HttpPostedFileBase;
                string filePath =
                    System.Web.HttpContext.Current.Server.MapPath(
                        ConfigurationManager.AppSettings["PublicationAvatarsPath"] + "\\" +
                        publication.Id + ".png");
                Image.SaveImage(hpf, filePath, 1000, 1000);
                publication.ImagePath = filePath;
                DB.Publications.Add(publication);
                DB.SaveChanges();
                PublicationChat chat = new PublicationChat();
                chat.Id = publication.Id;
                DB.Chats.Add(chat);
                DB.SaveChanges();
                return RedirectToAction("Index", "Home");
            }
            else
            {
                model.Categories = new SelectList(DB.PublicationCategories, "Id", "Name");
            }
            return View(model);
        }

        public ActionResult Index(int? page)
        {
            ApplicationDbContext DB = new ApplicationDbContext();
            List<PublicationViewModels.PartialPublication> result =
                new List<PublicationViewModels.PartialPublication>();
            var OrderedPublications = DB.Publications.OrderByDescending(m => m.DateTimeOfPublication);
            foreach (var publ in OrderedPublications)
            {
                string ImagePath;
                if (System.IO.File.Exists(publ.ImagePath))
                {
                    ImagePath = ConfigurationManager.AppSettings["PublicationAvatarsPath"] + "\\" +
                                publ.Id + ".png";
                }
                else
                {
                    ImagePath = ConfigurationManager.AppSettings["PublicationAvatarsPath"] +
                                "default.png";
                }
                List<ApplicationUser> subscribers = new List<ApplicationUser>();
                result.Add(new PublicationViewModels.PartialPublication()
                {
                    PublicationId = publ.Id,
                    PublicationName = publ.Name,
                    DateOfPublication = publ.DateTimeOfPublication.ToString(),
                    ImagePath = ImagePath.Remove(0, 1),
                    PublicationText = publ.Text,
                    Subscribers = publ.Subscriptions.ToList(),
                    Creator = (publ.Author.FirstName + " " + publ.Author.SurName),
                    DateOfMeet = publ.DateOfMeeting.ToString(@"MM\/dd\/yyyy HH:mm:ss")
                });
            }
            int pagesize = 3;
            int pagenumber = (page ?? 1);
            return View(result.ToPagedList(pagenumber, pagesize));
        }

        [HttpGet]
        public async Task<ActionResult> AddSubscriber(string id)
        {
            ApplicationDbContext _DB = new ApplicationDbContext();
            ApplicationUserManager userManager =
                new ApplicationUserManager(new UserStore<ApplicationUser>(_DB));
            Publication publication = await _DB.Publications.FirstOrDefaultAsync(p => p.Id == id);
            var userId = User.Identity.GetUserId();
            ApplicationUser currentUser = await userManager.Users.FirstOrDefaultAsync(user => user.Id == userId);
            var ifSubscribed = publication.Subscriptions.FirstOrDefault(user => user == currentUser);
            if (ifSubscribed == null)
            {
                publication.Subscriptions.Add(currentUser);
                _DB.SaveChanges();
            }


            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> DeleteSubscriber(string id)
        {
            ApplicationDbContext _DB = new ApplicationDbContext();
            ApplicationUserManager userManager =
                new ApplicationUserManager(new UserStore<ApplicationUser>(_DB));
            Publication publication = await _DB.Publications.FirstOrDefaultAsync(p => p.Id == id);
            var userId = User.Identity.GetUserId();
            ApplicationUser currentUser = await userManager.Users.FirstOrDefaultAsync(user => user.Id == userId);
            var ifSubscribed = publication.Subscriptions.FirstOrDefault(user => user == currentUser);
            if (ifSubscribed != null)
            {
                publication.Subscriptions.Remove(currentUser);
                _DB.SaveChanges();
            }


            return RedirectToAction("Index");
        }

        public bool IsSubscribedUser(ApplicationUser user)
        {
            return true;
        }
        //[ChildActionOnly]
        public ActionResult Sidebar()
        {
            List<MyMeetings.Models.PublicationViewModels.ShortPublicationModelView> result = new List<PublicationViewModels.ShortPublicationModelView>();
            var news = DB.Publications.OrderByDescending(m => m.DateTimeOfPublication).Take(3);
            foreach (var a in news)

                result.Add(new PublicationViewModels.ShortPublicationModelView
                {
                    Creator = a.Author.FirstName +" "+ a.Author.SurName,
                    DateOfMeet = a.DateOfMeeting.ToString(),
                    DateOfPublication = a.DateTimeOfPublication.ToString(),
                    ImagePath = a.ImagePath,
                    PublicationId = a.Id,
                    Category = a.Category.Name,
                    PublicationName = a.Name
                });   
            return PartialView(result);
        }



        //[HttpGet]
        //public ActionResult AddSubscriber(string id)
        //{
        //    ViewBag.PublicationID = id;
        //    return RedirectToAction("AddSubscribe");
        //}

        //[HttpPost]
        //public ActionResult AddSubscribe()
        //{
        //    var publication = _DB.Publications.FirstOrDefaultAsync(p => p.Id == ViewBag.p);
        //    return RedirectToAction("Index","Home");
        //}

    }
}

MyMeetings/MyMeetings/Views/Publications/Create.cshtml
@model MyMeetings.Models.PublicationViewModels.CreatePublicationModelView
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Scripts.Render("~/Scripts/jquery-1.12.4.js")
<h2>Create new meeting</h2>
@using (Html.BeginForm("Create", "Publications", FormMethod.Post, new { @class = "form-horizontal", role = "form", enctype = "multipart/form-data" }))
{
    <div  class="sidebar">@*@Html.Action("Sidebar")*@</div>
    @Html.AntiForgeryToken()
    <hr />
    <div class="flex-column">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="cc form-group flex-row">
            @Html.LabelFor(m => m.PublicationName,new { @class = "col-md-2 contol-label" })
                <div class="col-lg-6 col-md-8">
                    @Html.TextBoxFor(m => m.PublicationName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.PublicationName, "", new { @class = "text-danger" })
                 </div>
            </div>
        <div class="form-group flex-row">
            @Html.Label("Category", new { @class = "col-md-2 contol-label" })
            <div class="col-lg-6 col-md-8">
                @Html.DropDownListFor(m => m.CategoryID, @Model.Categories, "Please, select category", new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group flex-row">
            @Html.LabelFor(m => m.Text, new { @class = "col-md-2 contol-label" })
            <div class="flex-row">
                    <textarea class="input form-control" name="Text" rows="10"  onfocus="placeholder = ''" onblur="placeholder = 'Your text of publication:';" style="resize:none"></textarea>
                </div>
            @Html.ValidationMessageFor(m => m.Text, "", new { @class = "text-danger" })
        </div>
        <div class="flex-row form-group">
            @Html.LabelFor(model => model.DateOfMeeting, new { @class = "col-md-2 contol-label" })
                    <div class='input-group date datetimepicker col-lg-6 col-md-8'>
                        <input type='text' id="DateOfMeeting" name="DateOfMeeting" class="form-control" />
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                    </div>
                    @Html.ValidationMessageFor(model => model.DateOfMeeting, "Incorrect data format", new { @class = "text-danger" })
 
        </div>
        <div class="flex-row form-group">
            @Html.Label("Publication Image", new { @class = "col-md-2 contol-label" })
            <div class="input-group col-md-8 file_upload">
                <button type="button">Chose image</button>
                <div>Файл не выбран</div>
                <input type="file" id="imagefile" name="imagefile" />
            </div>
            <input type="file" id="imagefile2" name="imagefile2"/>
        </div>
            <div class="form-group flex-row">
                <div>
                    <input type="submit" class="btn btn-default" value="Create" />
                    <input type="submit" class="btn update" value="Update" />
                </div>
            </div>
        </div>
}
@section Scripts {
    @Scripts.Render("~/Scripts/jquery-1.12.4.js")
    @Scripts.Render("~/Scripts/CommonScripts/Publications/DatetimepickerInitializer.js")
    @Scripts.Render("~/Scripts/CommonScripts/Publications/FileNameForInputFileWrapper.js")
    @*@Scripts.Render("~/Scripts/CommonScripts/Publications/InputFileFiller.js");*@
    @Scripts.Render("~/Scripts/moment.min.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Styles.Render("~/Content/bootstrap-datetimepicker-build.css")
    @Styles.Render("~/content/pagestyles/publications-create.css")
    @*@Styles.Render("~/content/ucss-file-upload.css")*@
    @Styles.Render("~/content/datePicker.css")
    @Styles.Render("~/content/Site.css")
    @Styles.Render("https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css")
    <script type="text/javascript">
    $(document).ready(function () {
        setInterval(function () { $('.sidebar').load('@Url.Action("Sidebar")') }, 30000);
    </script>
    });
}

MyMeetings/MyMeetings/Views/Publications/Index.cshtml
@model PagedList.IPagedList<MyMeetings.Models.PublicationViewModels.PartialPublication>
@using Microsoft.AspNet.Identity
@using PagedList.Mvc;
@{
    ViewBag.Title = "Publications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Publications</h2>
<div>
    @*<div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>*@
  
        @foreach (var m in Model)
        {
            <div class="publication-div" style="clear: both; width: 100%; height: 100%; float: left">
                @*<input type="hidden" value="@m.PublicationId" class="PublicationId" />*@
                <div class="timer" value="@m.PublicationId">
                    <input type="hidden" value="@m.DateOfMeet"id="@m.PublicationId"/>
                </div>
                <div style="float: left">
                 
                    <img src=@m.ImagePath class="photocard">
                </div>
                <div style="float: left">
                    <p class="publication-header">@m.PublicationName </p>
                    <div class="div-description">@m.PublicationText</div>
                </div>
                <div class="publicattion-div" style="float: right">
                    <p>
                        @m.Subscribers.Count
                        <img src="~/Content/images/community.png" width="25" height="18">
                    </p>
                </div>



                <div style="float: right">
                    <p class="publication-text">Создал @m.Creator </p>
                    <p class="publication-text">Опубликовано @m.DateOfPublication </p>
                </div>
                @if (!@m.IsSubscribedUser)
                {
                    <div style="float: right">
                        <a class="btn btn-default publication-button" href="/Publications/AddSubscriber/@m.PublicationId" style="background-color: #b8860b">Subscribe</a>
                    </div>
                }
                else
                {
                    <div style="float: right">
                        <a class="btn btn-default publication-button" href="/Publications/DeleteSubscriber/@m.PublicationId" style="background-color: #b22222">UnSubscribe</a>
                    </div>

                }
                <a href="/Discuss?ChatId=@m.PublicationId">Перейти к обсуждению</a>
            </div>




        }

    <label class="checkbox-inline" id="list-of-roles">

    </label>
    <p>
        <a class="btn btn-default btn-save">Save</a>
    </p>

    <br /> Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page }))
</div>
@section Scripts {
    @Scripts.Render("~/scripts/commonscripts/Shared/Timer/jquery.min.js");
    @Scripts.Render("~/Scripts/CommonScripts/Publications/FlipCountDownInitializer.js");
    @Scripts.Render("~/scripts/commonscripts/Shared/Timer/jquery.flipcountdown.js");
    @Styles.Render("~/scripts/commonscripts/Shared/Timer/jquery.flipcountdown.css");
    @Scripts.Render("~/Scripts/CommonScripts/Manage/ValidateFileFormat.js");
    @Scripts.Render("~/bundles/jqueryval");
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js");
    @Scripts.Render("~/scripts/commonscripts/roles/roleanduserhandler.js");
    @Styles.Render("~/Content/PagedList.css");
    @Styles.Render("~/content/pagestyles/publications-show.css");


}
    @*<script type="text/javascript">

        $(function() {
            $.ajaxSetup({ cache: false });
            $(".userInfo").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}*@

MyMeetings/MyMeetings/Views/Publications/Show.cshtml
@model PagedList.IPagedList<MyMeetings.Models.PublicationViewModels.PartialPublication>
@using PagedList.Mvc;
@{
    ViewBag.Title = "Publications";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Пользователи</h2>
<div>
    @*<div id="modDialog" class="modal fade">
        <div id="dialogContent" class="modal-dialog"></div>
    </div>*@

        @foreach (var m in Model)
        {
            <div class="publication-div"   style="clear: both; width: 100%; height: 100%;float: left">
          
                <div style="float: left">
                    <img src=@m.ImagePath class="photocard">
                </div>
                <div style="float: left">
                    <p class="publication-header">@m.PublicationName </p>
                    <div class="div-description">@m.PublicationText</div>
                </div>
                <div class="publicattion-div" style="float:right">
                    <p>
                        @m.Subscribers.Count
                    <img src="~/Content/images/community.png" width="25" height="18">
                </p>
</div>



                <div style="float: right">
                    <p class="publication-text">Создал @m.Creator </p>
                    <p class="publication-text">Опубликовано @m.DateOfPublication </p>
                </div>
                    <div style="float: right">
                        <a class="btn btn-default publication-button" style="background-color: #b8860b">Subscribe</a>
                    </div>
                </div>

           
               
        }

    <label class="checkbox-inline" id="list-of-roles">

    </label>
    <p>
        <a class="btn btn-default btn-save">Save</a>
    </p>

    <br /> Страница @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) из @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Show", new { page }))
</div>
@section Scripts {
    @Scripts.Render("~/Scripts/CommonScripts/Manage/ValidateFileFormat.js");
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @Scripts.Render("~/scripts/commonscripts/roles/roleanduserhandler.js")
    @Styles.Render("~/ Content / PagedList.css")
    @Styles.Render("~/content/pagestyles/publications-show.css")
}
    @*<script type="text/javascript">

        $(function() {
            $.ajaxSetup({ cache: false });
            $(".userInfo").click(function(e) {
                e.preventDefault();
                $.get(this.href, function(data) {
                    $('#dialogContent').html(data);
                    $('#modDialog').modal('show');
                });
            });
        })
    </script>
}*@

MyMeetings/MyMeetings/Views/Publications/Sidebar.cshtml
@model IEnumerable<MyMeetings.Models.PublicationViewModels.ShortPublicationModelView>
<h3>Latest publications</h3>
<div style="float:left">
    @foreach (var m in Model)
    {
        <div class="form-group flex-row">
            <div>
                <h4><b>@m.PublicationName</b></h4>
                <p>@m.Creator" created new meet:</p>
                <p>@m.Category</p>
                <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866"> Read more &raquo;</a></p>
            </div>
        </div>
    }
</div>